name: "Daily Iris Inference - {environment}"
notebook_path: "/Repos/{environment}/ml-repo/notebooks/inference"
schedule: "0 0 * * *"
cluster:
  sparkVersion: "13.3.x-scala2.12"
  nodeTypeId: "Standard_F4s_v2"
  numWorkers: 1
  autoscale:
    minWorkers: 1
    maxWorkers: 2
tags:
  purpose: "inference"
  workflow_owner: "pochireddygari@gmail.com"
