name: "Daily Iris Inference - {environment}"
notebook_path: "/Repos/{environment}/ml-repo/notebooks/inference/inference_notebook"
schedule: "0 0 0 * * ?"
cluster:
  new_cluster:
    spark_version: "13.3.x-scala2.12"
    node_type_id: "r5d.large"
    num_workers: 2
    autotermination_minutes: 15
tags:
  purpose: "inference"
  workflow_owner: "pochireddygari@gmail.com"
