name: "Monthly Iris Training - {environment}"
notebook_path: "/Repos/{environment}/ml-repo/notebooks/train"
schedule: "0 0 1 * *"
cluster:
  spark_version: "13.3.x-scala2.12"
  node_type_id: "Standard_F4s"
  num_workers: 2
tags:
  purpose: "training"
  workflow_owner: "pochireddygari@gmail.com"
